/******************************************************************************\
* The Romualdo Language                                                        *
*                                                                              *
* Copyright 2020-2025 Leandro Motta Barros                                     *
* Licensed under the MIT license (see LICENSE.txt for details)                 *
\******************************************************************************/

// The vm package implements the Romualdo Virtual Machine, which executes the
// bytecode generated by the Romualdo Language Compiler.
package vm
