#
# The Romualdo Language
#
# Copyright 2024 Leandro Motta Barros
# Licensed under the MIT license (see LICENSE.txt for details)
#

name: Run Tests
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'
      - run: go test -v ./...
  end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'
      - run: go run ./cmd/romualdo/ dev test
